services:
  # Some things we could add:
  # - Dependency management between services
  # - Restart policies
  etl-server:
    build: .
    ports:
      - "5000:5000"
    environment:
      ROOT_DATA_PATH: ./data/
      DB_HOSTNAME: user-experiment-stats
      DB_PORT_NUM: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 2jXXTL2aSdKu8xFjpS9V_4lADSQlr55
  user-experiment-stats:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 2jXXTL2aSdKu8xFjpS9V_4lADSQlr55
    ports:
      - "5432:5432"
